#  LIST


In [2]:
lst = list([1,2,3,4,5])
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3, 4, 5]


In [5]:
lst1= [1,2,3,4,5]
print(type(lst1))

<class 'list'>


In [6]:
lst1.append(6)

In [7]:
lst1.insert(2,7)

In [8]:
print(lst1)

[1, 2, 7, 3, 4, 5, 6]


# SETS 
A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements. Python's set class represents the mathematical notion of a set.This is based on a data structure known as a hash table

In [9]:
set1={1,2,3,4,5}

In [10]:
print(type(set1))
print(set1)

<class 'set'>
{1, 2, 3, 4, 5}


# NumPy: The Foundation of Scientific Computing in Python

## Table of Contents
1. [What is NumPy?](#what-is-numpy)
2. [Why Use NumPy?](#why-use-numpy)
3. [Installation](#installation)
4. [Core Concepts](#core-concepts)
5. [Basic Usage](#basic-usage)
6. [Array Operations](#array-operations)
7. [Mathematical Functions](#mathematical-functions)
8. [Array Manipulation](#array-manipulation)
9. [Broadcasting](#broadcasting)
10. [Linear Algebra](#linear-algebra)
11. [Random Number Generation](#random-number-generation)
12. [File I/O](#file-io)
13. [Performance Tips](#performance-tips)
14. [Common Use Cases](#common-use-cases)
15. [Best Practices](#best-practices)

## What is NumPy?

**NumPy** (Numerical Python) is the fundamental package for scientific computing in Python. It provides:
- A powerful N-dimensional array object (`ndarray`)
- Sophisticated broadcasting functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

## Why Use NumPy?

### Performance Benefits
- **Speed**: NumPy arrays are stored in contiguous memory locations, making operations much faster than pure Python
- **Vectorization**: Operations are applied to entire arrays without explicit loops
- **Memory Efficiency**: Uses less memory than Python lists

### Functionality
- **Mathematical Operations**: Comprehensive mathematical functions
- **Broadcasting**: Perform operations on arrays of different shapes
- **Integration**: Works seamlessly with other scientific Python libraries

## Installation
bash
# Using pip
pip install numpy

# Using conda
conda install numpy

# Using conda-forge
conda install -c conda-forge numpy

## Core Concepts

### The ndarray Object
The core of NumPy is the `ndarray` (N-dimensional array) object:
- Homogeneous: All elements must be of the same type
- Fixed size: Size is determined at creation time
- Efficient: Stored in contiguous memory blocks
import numpy as np

# Creating arrays
arr = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr}")
print(f"Type: {type(arr)}")
print(f"Data type: {arr.dtype}")
print(f"Shape: {arr.shape}")
print(f"Size: {arr.size}")




## Basic Usage

### Creating Arrays
import numpy as np

# From Python lists
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2], [3, 4]])

# Using built-in functions
zeros = np.zeros((3, 4))          # Array of zeros
ones = np.ones((2, 3))            # Array of ones
empty = np.empty((2, 2))          # Uninitialized array
full = np.full((3, 3), 7)         # Array filled with 7

# Range arrays
arange = np.arange(0, 10, 2)      # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)   # [0, 0.25, 0.5, 0.75, 1]

# Random arrays
random = np.random.random((2, 3)) # Random values between 0 and 1
randint = np.random.randint(0, 10, (3, 3))  # Random integers

# Identity matrix
identity = np.eye(3)              # 3x3 identity matrix




### Array Attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape: {arr.shape}")        # (2, 3)
print(f"Size: {arr.size}")          # 6
print(f"Dimensions: {arr.ndim}")    # 2
print(f"Data type: {arr.dtype}")    # int64 (may vary)
print(f"Item size: {arr.itemsize}") # 8 bytes (may vary)




## Array Operations

### Indexing and Slicing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic indexing
print(arr[0])        # 0
print(arr[-1])       # 9

# Slicing
print(arr[2:5])      # [2 3 4]
print(arr[::2])      # [0 2 4 6 8]
print(arr[::-1])     # [9 8 7 6 5 4 3 2 1 0]

# 2D array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1, 2])   # 6
print(arr2d[1:, :2]) # [[4 5], [7 8]]




### Boolean Indexing
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean mask
mask = arr > 3
print(mask)          # [False False False True True True]
print(arr[mask])     # [4 5 6]

# Direct boolean indexing
print(arr[arr > 3])  # [4 5 6]
print(arr[(arr > 2) & (arr < 6)])  # [3 4 5]




### Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(arr[indices])  # [20 40 50]

# 2D fancy indexing
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2d[[0, 2], [1, 0]])  # [2 5]




## Mathematical Functions

### Arithmetic Operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise operations
print(a + b)         # [6 8 10 12]
print(a - b)         # [-4 -4 -4 -4]
print(a * b)         # [5 12 21 32]
print(a / b)         # [0.2 0.33 0.43 0.5]
print(a ** 2)        # [1 4 9 16]

# Scalar operations
print(a + 10)        # [11 12 13 14]
print(a * 2)         # [2 4 6 8]




### Universal Functions (ufuncs)
arr = np.array([1, 4, 9, 16, 25])

# Mathematical functions
print(np.sqrt(arr))     # [1. 2. 3. 4. 5.]
print(np.exp(arr))      # Exponential
print(np.log(arr))      # Natural logarithm
print(np.sin(arr))      # Sine
print(np.cos(arr))      # Cosine

# Aggregation functions
print(np.sum(arr))      # 55
print(np.mean(arr))     # 11.0
print(np.std(arr))      # Standard deviation
print(np.min(arr))      # 1
print(np.max(arr))      # 25




### Statistical Functions
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Along different axes
print(np.mean(data))           # 5.0 (overall mean)
print(np.mean(data, axis=0))   # [4. 5. 6.] (column means)
print(np.mean(data, axis=1))   # [2. 5. 8.] (row means)

# Other statistics
print(np.median(data))         # 5









In [13]:

import numpy as np

In [14]:
arr=np.array([1,2,3,4])

In [15]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [17]:
arr.shape

(4,)

In [18]:
arr.reshape(1,4)

array([[1, 2, 3, 4]])

In [20]:
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr1.shape
print(arr1)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [21]:
arr1.shape

(2, 5)

In [22]:
arr1.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5]])

In [24]:
arr1[:2,]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [25]:
np.random.randn(5,6)

array([[ 0.80695529,  0.84508768,  0.79690527,  1.412498  , -0.24423019,
         0.06167583],
       [ 1.88470111, -1.04670752, -0.45535835,  1.13777211,  1.10628823,
        -0.96591792],
       [ 0.14179469, -0.67893962,  0.15132251,  0.90826514, -0.91509668,
         0.97230795],
       [ 0.43497706,  0.44359368,  0.11033563, -0.18079306,  0.9381769 ,
        -1.584812  ],
       [ 1.25242232, -0.23611365, -1.62790475,  0.66936859, -0.55373891,
        -0.28821377]])

In [26]:
np.random.randint(10,50,4).reshape(2,2)

array([[34, 47],
       [25, 27]])